package payment

const domain = "https://api.mch.weixin.qq.com"

const riskGetPublicKeyURLSuffix = "https://fraud.mch.weixin.qq.com/risk/getpublickey"
const downloadBillURLSuffix = "/pay/downloadbill"
const unifiedOrderURLSuffix = "/pay/unifiedorder"
const orderQueryURLSuffix = "/pay/orderquery"
const microPayURLSuffix = "/pay/micropay"
const reverseURLSuffix = "/secapi/pay/reverse"
const closeOrderURLSuffix = "/pay/closeorder"
const refundURLSuffix = "/secapi/pay/refund"
const refundQueryURLSuffix = "/pay/refundquery"
const sendRedPackURLSuffix = "/mmpaymkttransfers/sendredpack"
const getHBInfoURLSuffix = "/mmpaymkttransfers/gethbinfo"
const sendGroupRedPackURLSuffix = "/mmpaymkttransfers/sendgroupredpack"
const getTransferInfoURLSuffix = "/mmpaymkttransfers/gettransferinfo"
const promotionTransfersURLSuffix = "/mmpaymkttransfers/promotion/transfers"
const mmPaySpTransQueryBankURLSuffix = "/mmpaysptrans/query_bank"
const mmPaySpTransPayBankURLSuffix = "/mmpaysptrans/pay_bank"
const authCodeToOpenidURLSuffix = "/tool/authcodetoopenid"
const BizPayURL = "weixin://wxpay/bizpayurl?"
const sandboxURLSuffix = "/sandboxnew"
const sandboxSignKeyURLSuffix = sandboxURLSuffix + "/pay/getsignkey"
