package payment

const RISK_GETPUBLICKEY_URL_SUFFIX = "https://fraud.mch.weixin.qq.com/risk/getpublickey"
const DOWNLOADBILL_URL_SUFFIX = "/pay/downloadbill"
const UNIFIEDORDER_URL_SUFFIX = "/pay/unifiedorder"
const ORDERQUERY_URL_SUFFIX = "/pay/orderquery"
const MICROPAY_URL_SUFFIX = "/pay/micropay"
const REVERSE_URL_SUFFIX = "/secapi/pay/reverse"
const CLOSEORDER_URL_SUFFIX = "/pay/closeorder"
const REFUND_URL_SUFFIX = "/secapi/pay/refund"
const REFUNDQUERY_URL_SUFFIX = "/pay/refundquery"
const SENDREDPACK_URL_SUFFIX = "/mmpaymkttransfers/sendredpack"
const GETHBINFO_URL_SUFFIX = "/mmpaymkttransfers/gethbinfo"
const SENDGROUPREDPACK_URL_SUFFIX = "/mmpaymkttransfers/sendgroupredpack"
const GETTRANSFERINFO_URL_SUFFIX = "/mmpaymkttransfers/gettransferinfo"
const PROMOTION_TRANSFERS_URL_SUFFIX = "/mmpaymkttransfers/promotion/transfers"
const MMPAYSPTRANS_QUERY_BANK_URL_SUFFIX = "/mmpaymkttransfers/mmpaysptrans/query_bank"
const MMPAYSPTRANS_PAY_BANK_URL_SUFFIX = "/mmpaymkttransfers/mmpaysptrans/pay_bank"
const AUTHCODETOOPENID_URL_SUFFIX = "/tools/authcodetoopenid"
