package official

const ClearQuotaUrlSuffix = "/cgi-bin/clear_quota"
const GetCallbackIPUrlSuffix = "/cgi-bin/getcallbackip"

const GetKFListUrlSuffix = "/cgi-bin/customservice/getkflist"

const MenuCreateUrlSuffix = "/cgi-bin/menu/create"
const MenuGetUrlSuffix = "/cgi-bin/menu/get"
const MenuDeleteUrlSuffix = "/cgi-bin/menu/delete"
const MenuAddConditionalUrlSuffix = "/cgi-bin/menu/addconditional"
const MenuDeleteConditionalUrlSuffix = "/cgi-bin/menu/delconditional"
const MenuTryMatchUrlSuffix = "/cgi-bin/menu/trymatch"
const GetCurrentSelfMenuInfoUrlSuffix = "/cgi-bin/get_current_selfmenu_info"

const ApiSetIndustryUrlSuffix = "/cgi-bin/template/api_set_industry"
const GetIndustryUrlSuffix = "/cgi-bin/template/get_industry"
const ApiAddTemplateUrlSuffix = "/cgi-bin/template/api_add_template"
const GetAllPrivateTemplateUrlSuffix = "/cgi-bin/template/get_all_private_template"
const DelPrivateTemplateUrlSuffix = "/cgi-bin/template/del_private_template"
const MessageTemplateSendUrlSuffix = "/cgi-bin/message/template/send"

const MediaUploadUrlSuffix = "/cgi-bin/media/upload"
const MediaUploadImgUrlSuffix = "/cgi-bin/media/uploadimg"
const MediaGetUrlSuffix = "/cgi-bin/media/get"
const MediaGetJssdkUrlSuffix = "/cgi-bin/media/get/jssdk"

const TagsCreateUrlSuffix = "/cgi-bin/tags/create"
const TagsGetUrlSuffix = "/cgi-bin/tags/get"
const TagsUpdateUrlSuffix = "/cgi-bin/tags/update"
const TagsDeleteUrlSuffix = "/cgi-bin/tags/delete"

const UserTagGetUrlSuffix = "/cgi-bin/user/tag/get"
const TagsMembersBatchTaggingUrlSuffix = "/cgi-bin/tags/members/batchtagging"
const TagsMembersBatchUntaggingUrlSuffix = "/cgi-bin/tags/members/batchuntagging"
const TagsGetIdListUrlSuffix = "/cgi-bin/tags/getidlist"
const TagsMembersGetBlackListUrlSuffix = "/cgi-bin/tags/members/getblacklist"
const TagsMembersBatchBlackListUrlSuffix = "/cgi-bin/tags/members/batchblacklist"
const TagsMembersBatchUnblackListUrlSuffix = "/cgi-bin/tags/members/batchunblacklist"

const UserInfoUpdateRemarkUrlSuffix = "/cgi-bin/user/info/updateremark"
const UserInfoUrlSuffix = "/cgi-bin/user/info"
const UserInfoBatchGetUrlSuffix = "/cgi-bin/user/info/batchget"
const UserGetUrlSuffix = "/cgi-bin/user/get"

const QRCODE_CREATE_URL_SUFFIX = "/cgi-bin/qrcode/create"
const SHOWQRCODE_URL_SUFFIX = "/cgi-bin/showqrcode"

const DATACUBE_TIME_LAYOUT = "2006-01-02"

// const tags_members_batchuntagging_URL_SUFFIX = "/cgi-bin/tags/members/batchuntagging"
// const tags_members_batchtagging_URL_SUFFIX = "/cgi-bin/tags/members/batchtagging"
// const tags_members_batchuntagging_URL_SUFFIX = "/cgi-bin/tags/members/batchuntagging"
const DATACUBE_GETUSERSUMMARY_URL_SUFFIX = "/datacube/getusersummary"
const DATACUBE_GETUSERCUMULATE_URL_SUFFIX = "/datacube/getusercumulate"
const DATACUBE_GETARTICLESUMMARY_URL_SUFFIX = "/datacube/getarticlesummary"
const DATACUBE_GETARTICLETOTAL_URL_SUFFIX = "/datacube/getarticletotal"
const DATACUBE_GETUSERREAD_URL_SUFFIX = "/datacube/getuserread"
const DATACUBE_GETUSERREADHOUR_URL_SUFFIX = "/datacube/getuserreadhour"
const DATACUBE_GETUSERSHARE_URL_SUFFIX = "/datacube/getusershare"
const DATACUBE_GETUSERSHAREHOUR_URL_SUFFIX = "/datacube/getusersharehour"

const DATACUBE_GETUPSTREAMMSG_URL_SUFFIX = "/datacube/getupstreammsg"
const DATACUBE_GETUPSTREAMMSGHOUR_URL_SUFFIX = "/datacube/getupstreammsghour"
const DATACUBE_GETUPSTREAMMSGWEEK_URL_SUFFIX = "/datacube/getupstreammsgweek"
const DATACUBE_GETUPSTREAMMSGDIST_URL_SUFFIX = "/datacube/getupstreammsgdist"
const DATACUBE_GETUPSTREAMMSGMONTH_URL_SUFFIX = "/datacube/getupstreammsgmonth"
const DATACUBE_GETUPSTREAMMSGDISTWEEK_URL_SUFFIX = "/datacube/getupstreammsgdistweek"
const DATACUBE_GETUPSTREAMMSGDISTMONTH_URL_SUFFIX = "/datacube/getupstreammsgdistmonth"
const DATACUBE_GETINTERFACESUMMARY_URL_SUFFIX = "/datacube/getinterfacesummary"
const DATACUBE_GETINTERFACESUMMARYHOUR_URL_SUFFIX = "/datacube/getinterfacesummaryhour"

const MATERIAL_ADD_NEWS_URL_SUFFIX = "/cgi-bin/material/add_news"
const MATERIAL_ADD_MATERIAL_URL_SUFFIX = "/cgi-bin/material/add_material"
const MATERIAL_GET_MATERIAL_URL_SUFFIX = "/cgi-bin/material/get_material"
const MATERIAL_DEL_MATERIAL_URL_SUFFIX = "/cgi-bin/material/del_material"
const MATERIAL_UPDATE_NEWS_URL_SUFFIX = "/cgi-bin/material/update_news"
const MATERIAL_GET_MATERIALCOUNT_URL_SUFFIX = "/cgi-bin/material/get_materialcount"
const MATERIAL_BATCHGET_MATERIAL_URL_SUFFIX = "/cgi-bin/material/batchget_material"
const COMMENT_OPEN_URL_SUFFIX = "/cgi-bin/comment/open"
const COMMENT_CLOSE_URL_SUFFIX = "/cgi-bin/comment/close"
const COMMENT_LIST_URL_SUFFIX = "/cgi-bin/comment/list"
const COMMENT_MARKELECT_URL_SUFFIX = "/cgi-bin/comment/markelect"
const COMMENT_UNMARKELECT_URL_SUFFIX = "/cgi-bin/comment/unmarkelect"
const COMMENT_DELETE_URL_SUFFIX = "/cgi-bin/comment/delete"
const COMMENT_REPLY_ADD_URL_SUFFIX = "/cgi-bin/comment/reply/add"
const COMMENT_REPLY_DELETE_URL_SUFFIX = "/cgi-bin/comment/reply/delete"

const OAUTH2_ACCESS_TOKEN_URL_SUFFIX = "/sns/oauth2/access_token"
const OAUTH2_REFRESH_TOKEN_URL_SUFFIX = "/sns/oauth2/refresh_token"
const OAUTH2_USERINFO_URL_SUFFIX = "/sns/userinfo"
const OAUTH2_AUTH_URL_SUFFIX = "/sns/auth"

const OAUTH2_AUTHORIZE_URL_SUFFIX = "https://open.weixin.qq.com/connect/oauth2/authorize"
const DEFAULT_OAUTH_REDIRECT_URL_SUFFIX = "/oauth_redirect"

const SNSAPI_BASE = "snsapi_base"
const SNSAPI_USERINFO = "snsapi_userinfo"

const GETTICKET_URL_SUFFIX = "/cgi-bin/ticket/getticket"

const CARD_LANDINGPAGE_CREATE_URL_SUFFIX = "/card/landingpage/create"
const CARD_CODE_DEPOSIT_URL_SUFFIX = "/card/code/deposit"
const CARD_CODE_GETDEPOSITCOUNT_URL_SUFFIX = "/card/code/getdepositcount"
const CARD_QRCODE_CREATE_URL_SUFFIX = "/card/qrcode/create"
const CARD_CODE_CHECKCODE_URL_SUFFIX = "/card/code/checkcode"
const CARD_CODE_GET_URL_SUFFIX = "/card/code/get"
const CARD_MPNEWS_GETHTML_URL_SUFFIX = "/card/mpnews/gethtml"
const CARD_TESTWHITELIST_SET_URL_SUFFIX = "/card/testwhitelist/set"
const CARD_CREATE_URL_SUFFIX = "/card/create"

const POI_ADDPOI_URL_SUFFIX = "/cgi-bin/poi/addpoi"
const POI_GETPOI_URL_SUFFIX = "/cgi-bin/poi/getpoi"
const POI_UPDATEPOI_URL_SUFFIX = "/cgi-bin/poi/updatepoi"
const POI_GETLISTPOI_URL_SUFFIX = "/cgi-bin/poi/getpoilist"
const POI_DELPOI_URL_SUFFIX = "/cgi-bin/poi/delpoi"
const POI_GETWXCATEGORY_URL_SUFFIX = "/cgi-bin/poi/getwxcategory"
