package official_account

const CLEAR_QUOTA_URL_SUFFIX = "/cgi-bin/clear_quota"
const GETCALLBACKIP_URL_SUFFIX = "/cgi-bin/getcallbackip"

const GETKFLIST_URL_SUFFIX = "/cgi-bin/customservice/getkflist"

const MENU_CREATE_URL_SUFFIX = "/cgi-bin/menu/create"
const MENU_GET_URL_SUFFIX = "/cgi-bin/menu/get"
const MENU_DELETE_URL_SUFFIX = "/cgi-bin/menu/delete"
const MENU_ADDCONDITIONAL_URL_SUFFIX = "/cgi-bin/menu/addconditional"
const MENU_DELETECONDITIONAL_URL_SUFFIX = "/cgi-bin/menu/delconditional"
const MENU_TRYMATCH_URL_SUFFIX = "/cgi-bin/menu/trymatch"
const GET_CURRENT_SELFMENU_INFO_URL_SUFFIX = "/cgi-bin/get_current_selfmenu_info"

const API_SET_INDUSTRY_URL_SUFFIX = "/cgi-bin/template/api_set_industry"
const GET_INDUSTRY_URL_SUFFIX = "/cgi-bin/template/get_industry"
const API_ADD_TEMPLATE_URL_SUFFIX = "/cgi-bin/template/api_add_template"
const GET_ALL_PRIVATE_TEMPLATE_URL_SUFFIX = "/cgi-bin/template/get_all_private_template"
const DEL_PRIVATE_TEMPLATE_URL_SUFFIX = "/cgi-bin/template/del_private_template"
const MESSAGE_TEMPLATE_SEND_URL_SUFFIX = "/cgi-bin/message/template/send"

const MEDIA_UPLOAD_URL_SUFFIX = "/cgi-bin/media/upload"
const MEDIA_UPLOADIMG_URL_SUFFIX = "/cgi-bin/media/uploadimg"
const MEDIA_GET_URL_SUFFIX = "/cgi-bin/media/get"
const MEDIA_GET_JSSDK_URL_SUFFIX = "/cgi-bin/media/get/jssdk"

const TAGS_CREATE_URL_SUFFIX = "/cgi-bin/tags/create"
const TAGS_GET_URL_SUFFIX = "/cgi-bin/tags/get"
const TAGS_UPDATE_URL_SUFFIX = "/cgi-bin/tags/update"
const TAGS_DELETE_URL_SUFFIX = "/cgi-bin/tags/delete"

const USER_TAG_GET_URL_SUFFIX = "/cgi-bin/user/tag/get"
const TAGS_MEMBERS_BATCHTAGGING_URL_SUFFIX = "/cgi-bin/tags/members/batchtagging"
const TAGS_MEMBERS_BATCHUNTAGGING_URL_SUFFIX = "/cgi-bin/tags/members/batchuntagging"
const TAGS_GETIDLIST_URL_SUFFIX = "/cgi-bin/tags/getidlist"
const TAGS_MEMBERS_GETBLACKLIST_URL_SUFFIX = "/cgi-bin/tags/members/getblacklist"
const TAGS_MEMBERS_BATCHBLACKLIST_URL_SUFFIX = "/cgi-bin/tags/members/batchblacklist"
const TAGS_MEMBERS_BATCHUNBLACKLIST_URL_SUFFIX = "/cgi-bin/tags/members/batchunblacklist"

const USER_INFO_UPDATEREMARK_URL_SUFFIX = "/cgi-bin/user/info/updateremark"
const USER_INFO_URL_SUFFIX = "/cgi-bin/user/info"
const USER_INFO_BATCHGET_URL_SUFFIX = "/cgi-bin/user/info/batchget"
const USER_GET_URL_SUFFIX = "/cgi-bin/user/get"

const QRCODE_CREATE_URL_SUFFIX = "/cgi-bin/qrcode/create"
const SHOWQRCODE_URL_SUFFIX = "/cgi-bin/showqrcode"

const DATACUBE_TIME_LAYOUT = "2006-01-02"

// const tags_members_batchuntagging_URL_SUFFIX = "/cgi-bin/tags/members/batchuntagging"
// const tags_members_batchtagging_URL_SUFFIX = "/cgi-bin/tags/members/batchtagging"
// const tags_members_batchuntagging_URL_SUFFIX = "/cgi-bin/tags/members/batchuntagging"
const DATACUBE_GETUSERSUMMARY_URL_SUFFIX = "/datacube/getusersummary"
const DATACUBE_GETUSERCUMULATE_URL_SUFFIX = "/datacube/getusercumulate"
const DATACUBE_GETARTICLESUMMARY_URL_SUFFIX = "/datacube/getarticlesummary"
const DATACUBE_GETARTICLETOTAL_URL_SUFFIX = "/datacube/getarticletotal"
const DATACUBE_GETUSERREAD_URL_SUFFIX = "/datacube/getuserread"
const DATACUBE_GETUSERREADHOUR_URL_SUFFIX = "/datacube/getuserreadhour"
const DATACUBE_GETUSERSHARE_URL_SUFFIX = "/datacube/getusershare"
const DATACUBE_GETUSERSHAREHOUR_URL_SUFFIX = "/datacube/getusersharehour"

const DATACUBE_GETUPSTREAMMSG_URL_SUFFIX = "/datacube/getupstreammsg"
const DATACUBE_GETUPSTREAMMSGHOUR_URL_SUFFIX = "/datacube/getupstreammsghour"
const DATACUBE_GETUPSTREAMMSGWEEK_URL_SUFFIX = "/datacube/getupstreammsgweek"
const DATACUBE_GETUPSTREAMMSGDIST_URL_SUFFIX = "/datacube/getupstreammsgdist"
const DATACUBE_GETUPSTREAMMSGMONTH_URL_SUFFIX = "/datacube/getupstreammsgmonth"
const DATACUBE_GETUPSTREAMMSGDISTWEEK_URL_SUFFIX = "/datacube/getupstreammsgdistweek"
const DATACUBE_GETUPSTREAMMSGDISTMONTH_URL_SUFFIX = "/datacube/getupstreammsgdistmonth"
const DATACUBE_GETINTERFACESUMMARY_URL_SUFFIX = "/datacube/getinterfacesummary"
const DATACUBE_GETINTERFACESUMMARYHOUR_URL_SUFFIX = "/datacube/getinterfacesummaryhour"

const MATERIAL_ADD_NEWS_URL_SUFFIX = "/cgi-bin/material/add_news"
const MATERIAL_ADD_MATERIAL_URL_SUFFIX = "/cgi-bin/material/add_material"
const MATERIAL_GET_MATERIAL_URL_SUFFIX = "/cgi-bin/material/get_material"
const MATERIAL_DEL_MATERIAL_URL_SUFFIX = "/cgi-bin/material/del_material"
const MATERIAL_UPDATE_NEWS_URL_SUFFIX = "/cgi-bin/material/update_news"
const MATERIAL_GET_MATERIALCOUNT_URL_SUFFIX = "/cgi-bin/material/get_materialcount"
const MATERIAL_BATCHGET_MATERIAL_URL_SUFFIX = "/cgi-bin/material/batchget_material"
const COMMENT_OPEN_URL_SUFFIX = "/cgi-bin/comment/open"
const COMMENT_CLOSE_URL_SUFFIX = "/cgi-bin/comment/close"
const COMMENT_LIST_URL_SUFFIX = "/cgi-bin/comment/list"
const COMMENT_MARKELECT_URL_SUFFIX = "/cgi-bin/comment/markelect"
const COMMENT_UNMARKELECT_URL_SUFFIX = "/cgi-bin/comment/unmarkelect"
const COMMENT_DELETE_URL_SUFFIX = "/cgi-bin/comment/delete"
const COMMENT_REPLY_ADD_URL_SUFFIX = "/cgi-bin/comment/reply/add"
const COMMENT_REPLY_DELETE_URL_SUFFIX = "/cgi-bin/comment/reply/delete"

const OAUTH2_ACCESS_TOKEN_URL_SUFFIX = "/sns/oauth2/access_token"
const OAUTH2_REFRESH_TOKEN_URL_SUFFIX = "/sns/oauth2/refresh_token"
const OAUTH2_USERINFO_URL_SUFFIX = "/sns/userinfo"
const OAUTH2_AUTH_URL_SUFFIX = "/sns/auth"

const OAUTH2_AUTHORIZE_URL_SUFFIX = "https://open.weixin.qq.com/connect/oauth2/authorize"
const DEFAULT_OAUTH_REDIRECT_URL_SUFFIX = "/oauth_redirect"

const SNSAPI_BASE = "snsapi_base"
const SNSAPI_USERINFO = "snsapi_userinfo"

const GETTICKET_URL_SUFFIX = "/cgi-bin/ticket/getticket"

const CARD_LANDINGPAGE_CREATE_URL_SUFFIX = "/card/landingpage/create"
const CARD_CODE_DEPOSIT_URL_SUFFIX = "/card/code/deposit"
const CARD_CODE_GETDEPOSITCOUNT_URL_SUFFIX = "/card/code/getdepositcount"
const CARD_QRCODE_CREATE_URL_SUFFIX = "/card/qrcode/create"
const CARD_CODE_CHECKCODE_URL_SUFFIX = "/card/code/checkcode"
const CARD_CODE_GET_URL_SUFFIX = "/card/code/get"
const CARD_MPNEWS_GETHTML_URL_SUFFIX = "/card/mpnews/gethtml"
const CARD_TESTWHITELIST_SET_URL_SUFFIX = "/card/testwhitelist/set"
const CARD_CREATE_URL_SUFFIX = "/card/create"
